### PR TITLE
Gradle, Travis-CI and unit tests configuration with one bugfix

### PR DESCRIPTION
**Pull request by skrzyneckik**
At first time I was thinking about splitting this PR to few small ones, but from the other hand those changes apply proper base for future development of this library:
- using Gradle as build tool will simplify settings project for everybody who is interested in this library,
- Travis-CI handles continues integration - whenever new PR is applied, whole build process with tests will be run,
- speaking about tests - Codecov with Jococo plugin will show what's code coverage

Just to make sure that Travis-CI with Codecov work, I've applied few simple unit tests for Utils.java ,
Moreover there was an issue with building 'from' clause. 

@reinaldoarrosi please let me know what do you think.

### CODE REVIEW

**Comment by bogdanRada** [comment]
any updates on this? i would love to be able to add this into my Android project using Graddle :D

**Comment by reinaldoarrosi** [comment]
Sorry! Last few weeks were very busy. I'll try to look into this over the weekend.

**Comment by reinaldoarrosi** [comment]
Merged, but I wasn't able to setup Travis-CI and Codecov yet.
I'll try to do it over the next week.

**Comment by bogdanRada** [comment]
Awesome but could you add documentation on how this can Be installed using graddle? 

That would Be very helpful. 

Thank you very much :)

**Comment by skrzyneckik** [comment]
@bogdanRada @reinaldoarrosi for now I've just applied build process to use gradle. We need to add plugin to push release build to maven central/jCenter as well - I'll create an issue for it

**Comment by bogdanRada** [comment]
Thanks a lot :)

**Comment by skrzyneckik** [comment]
I've created #6 resolve this publish issue

**Pull request merged**
